
language: php
sudo: false
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.23.2

php:
 - 7.2

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

script: composer run test

after_script:
- docker-compose down